version: '3.9'

services:
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
